name: work_log
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  flutter_hooks:
  riverpod_annotation:
  firebase_analytics:
  freezed_annotation:
  cupertino_icons: ^1.0.2
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider:
  intl: ^0.19.0
  go_router: ^13.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  riverpod_generator:
  freezed:
  json_serializable: 

flutter:
  uses-material-design: true

  assets:
    - assets/
